import java.util.Random;

public class Main {
	
	//testing done here. 
	
    public static void main(String[] args){
    	int tests = 1;
        long startTime = System.currentTimeMillis(); // for testing run speed
        for(int i = 0; i < tests; i ++) {
        	
    	    System.out.println(Kata6.whoLikesIt("Max", "John", "Mark"));
    	    
        }
        long stopTime = System.currentTimeMillis();
        long elapsedTimeAVG = stopTime - startTime;
        System.out.println("average run-time per " + tests + " tests: " + elapsedTimeAVG);
        System.out.println("average run-time per test: " + elapsedTimeAVG / tests);

    }
	
	
	
	
	
	/* testing for kata 2
    public static void main(String[] args){
    	int tests = 100;
        long startTime = System.currentTimeMillis(); // for testing run speed
        for(int i = 0; i < tests; i ++) {
        	System.out.println(Kata2.triangle(getSaltString()));

        	//System.out.println(Kata2.triangle2("RRGBBBBRRRBRBRGRBGRRRRGBBRBGBGGRRGRBGBGBRBGBBGRBGBBBBGRBRRBGBRRGGRRBRGGRBRBGRGGBRBGRBGGRRRRBGGGBGBRGRGRRRBBRGRRBBRGRGGRBGRRGRRGBBGRRRGBBRGGBRRRRGGGBBBRGBGRGGBGGRBRRBRRBRBGRBBGRRBBGRBRRGGGRRBRBGGRGRGGRBGGBBGRRGBBRRGGRRBRRRGGBBRBBGRGBRRRBGRGGRRRRBRGBBRBRRRBBBBBGGGRBRBGBRBGRGRRGBRRGGRRGRBBGBRRRBRGGGGGRGRRRGGGRGBGRBBBRRBGGBBRRBRBRBGGGBBRGGGRRRBRBBRRBBBBGRBGGRGBBGGRRBRBGBGRGGGRRBBBGGBRRRGRRRBBGRGGRGBRGRBGBBRGBRGBRRGGRRGRGGGRGBBBGGBBBGBBGBRBRBBRBGGGRRBBGRGGRBBGRBBBBGRBRRBRGGGRBRBBBGGRBGBRGGBRBBBGRRRGGBBBRBGBRGBBBBRRBGRBBBGBRRGBRGGBRBRGGGBBRBGBRGGRRGGBGBRGGGBGGGBBBRRRBGRGGRGBBGBRBBBGRRRGRRRRBBGGBBGRGBGGRGBBBBGGRBGBGRBGGBGGRRRGGBBRGBBRRBGGBRRRBRRRGGRBBGBRBBGRGGRBRGGBBRRRGBRRRBRBBGRRGGRRRRGRRGRBRGGRBGGRRBRRRGRRGRRRRGRBBGGRRRRRBBGRGGGBRGGBBGRRBBGRGBGGBGRBRBRGBRBGRBBGRGBRRGRGBRBGRGRBBRBGBRBBRRRBGRBGGGGGRBGGGBGRBGRGRBBRGRGGGRRRBBBRBBGBRGGRBRBBRRRGGBBGRRGBRGRRRRGGGGRBBBGGGRRBGGRRGGGBRRRRRBGRGRGGRGBBGGGRGRGRRBGRGGRBBGGBGRRGRGBBRBRRRGGBRBBGGRBRRRGBRGGBRBRGGGGBRBGRBBGRRGBGGBRBBGRGBRBGRRGGBGRGRRGGRRBBGRGBGBRGRBRGRGGBRBRRRGRBGBBGRGRRBGRBBBBBBRRGRGBRRGBGBGRBGBBBRGGBRRGRBRBBRRBBGBGRBGRBRGBGGRRRRGRGBRBBBGRBRGGGBGRRRBGGRGGRGRRBGBGGRBGBGGBBGBRBGGGGBBGRBRGGRRRBBRRBBRGBBRRGBRGBRBRBGRBRGBRGBGBRRRRGGBRGBBGBGBGGRRGRGBRGRRRBBBGRBRRBGRBBGGBRRRBBGBRRGRGGBRRBGGBRRGRRRGBGRRBGGGRRRGRRRBRGGGRBGGRRRGBGBGGGBBGRGRBGBRBBBBRBGRBGRGBBGBBBGRBGRBGGRGRBGBRRBRRRRBBBRRBRBRRBRBRGGGBGBBGRRGBBBBGGBGRBRBRBBRGBGRRGGBGGGGBBGRRGRRGRRGRRRBBBBBBGBRRBGBGGBBGBRGBGRRGBGGRGRBRGRGGGRRGBBRGRRRBGRGBRGBBBRGGBRGBGBGBRBBGGGGBRBBGRRRGGRRRRRRGBRRBGBRRBBRRGRRBGBRRBBGRGBBRRGGBBGRRRBRGGRBBBGBBGRBBBGBGGBGRGRGRGBGRBBGRGGRRBBBGGGRBGRBGGBRBRRBBRBBBBRGGRRGBRGRBRGRRGBBRGRGRGBRRGBGRGGRBRRBGGBRRGBRRRRRRBGBBRBGGGGRBGRRBBRGRRGGRGBBBGBBBRBBRBBGBGRRBRGRGRBRGBRRBRRGGBGGBGRGGBGRRGRBGRBGBBRGRGRBRRRBRRRGBGGBRBGBBRBRRRGBGRGBBGRBBGBBGBGBGGGRBGGGBRRBGBBBRBGGRBBRBRGBBGBGBBBGBRGBBRGGBRGBRBBBBRGRRGBBBBRRBRBGRRGBGGRRGBGGBBGGBGGRRGRGRBGBGGRRBBBGRBBRGRGGGGBGGRGGGRBBRBBGRGGBRBRGRGBGRGBRRRRGRGRGRBGBGGBBBGRBGRBRGRGBRRRGBBBGGRGGGRRGGGRRGRRGRRBBRBRBGGGGRRRGRBGRBGBGRGGBBGGBBBRRRRGGBRRRRRBRRRGBBGBRRGRGGBGRBRBBGRBRBRGBRRBRBRRRGBRRGBBBRBRGGBBGGRGGRRBBGRRBGGRRRGGRGGRRGGRBGBGGRGBGGRGRRBBRGRGGRBBGGGBGGBGGGRBGRBGGBGBBBGRBGBRBBGBRRBRBRRGGRRGGBBGBGGGRRBRRRBRRRGGBRGRBRRGBBGBGGRGGGRRRBBGRBGRRBBRBGGGBBBBBBGGRBBGRBRBGGRBRGBRRBBBBGRBRBBBBRRGRRRRGBBBRRRRGBBGBGBBGRRRRRRGGBRRRGBGRRBGRRGGGRGBBGBGGBRBGBBBBBBBRBGGGBGRBGRRRGGGBRBBRBRRGGGBBRRRRGGRRBRGGBRRBGRBRGGGRRBGBRGBRRGGRRGRRBGGRBGGBRRGRBGGBGBGGGGBBRBRBGBBRRGGBRBRGBGGGBBGBGBRBRRGBBRBRBRBRRBBGGGBGBBGGBRGRRGBGGBBGGGBRBRGRRRBRBGGGGGRGGGRBBRGGRRRBRRGBBRRGGBGBBGGBRRRBGGRGBRRBRRBBBRGGGGGRRGGBRBGRGBGGBBGGGRBGBGBBGRGRGRRBRBBGBGRGRBBBBRBRGRRRBGGRGBGBBRRBRRGBGGRBGRBRGRRGGGGBBBGGBRRGRRBGBGRBBBGBRBBGBGBGBBRBRGBGRGRGGRBRBGBRGGGRBRRRRRBGRBGGRBGBBBRRBBBBRBBRGGRGRRRBBGBGBBBRBGBGBRRGRRBGRBRBGBGRRGBRBGRGGGRRRBRBGRBGGBRBBBBBGRGGRBRBRRGBBBGGRGGBBBGBGRRBRBRRRGRRBRRGGRRBGGRRBGRGBBRBBBGRRGRRBBBGGBBRRGBRRRGBBGGRRGGRGRGGRRRBRRRGRRRBRBRGGRBGBGRBRGGRRRGGRGRGBRRRRRGGBGRBBBBGBRRBBGBGBGBRGBBRBRGRRRRRGBGBRBRBGGBGRBRGGGGBRBBBBRRRGRGBBGBGRRGBGBBGGRRRRGRGBGRRGGGRRGRGRGGGGBBBRRBBBGRRRRRRGGBRRBGRBGRGGRRGGBBBGRBBRGBBBBRBRRGRBGRGGBGRGBBGRBBRRRGGRRRRBRBGBRRGBGGBBGGRRBBRBRBBRGRRRBGGRBRBBBRRGRRGGGGGBGGBGRRBBGBGGRRRRBBGGGGRGGRBGGRRGGRGRRBRBBRGBGRGGGRBGGBBBBBBBRRGRGBBBRBRRRGGGGBGRBGRGRRBBRRBGRRRRGBRRGGRBGRBGBBBGGGRGBGGRRBBBBRGGRGGRGRBBGGRGRBBRRBGGGGGBGGRRGGGGGRGBRRGBRGGGGBGBGGBBRBBBRGBBBGGBRBRGBBBGBRGBRBBGGRGRBBBGGBRGGRRGRGRGRRRRGRGRGBRBRGBBBGBGGBBGRGGBRRBGGGRRBGRBBBBRGRGGBBRGGBBGRRBBGRGGBBRBBBRGRBRGBRBBGBRBGRRRGBBRRRRBRBBBGRGGGBGGRBGBRR"));
            //System.out.println(Kata2.triangle("BGGBRGRBRRGBGBGGBRBGGGGBRRRRRBGBGGRBRGRBBRGGGGBBGRBRGRBRRGGRBGGBGGRGGGGGRRBRGBBGBBBGRBRRBGBRGGBGRRRRBRGRBRRGBGBRRGGBGBBGBBGGRBRGBGBGRBBBRBRGBBGRBRGBRBBRBGRRRRGGBGBRBRGRGBBRRGRRRRBRRGBBGGGRRRBRBGGBBBBBGRBRBRGRBBBBGRGGGBRRBRRGBGGBRBRGGGGBGGBBRBBGRGGGBGGRGBGGBBGBRGRRGBGRBRBGRGBRGBRBBGBBGGRGRBBBRBGBRRBGGBGGGRGRBGGRBRRBRRGBRBGBRBGBBBBGGGGRBRGBGBGRBBBGRGGRGBRBBBGRBRGGBGBBBGBGRRGBGBRRGGRRBRGGRBBGRGBGBBGGBRBBBRBBBBRRBRBGBGGGRGRRGGGRRRRRRGGGGBRRRRRGBGRBBRRBGBBGGRGRRRGRBGBBBRBBRBRRGGGGGRRBBGRBGRRGGRBRBRBRBBGGRBBRBBBBBBBGBRBGBGRRBRBGRGRRGRRRRBRGBRBGRGRRBGBBRBGGGBRGRBBGBGRGRGBBRRGRGRBGRBBRGRGBBGRRRGGRRGRGRGRBGRGRRGBBGBGRRRBBGGBGGRGGGRBRRBBBGGGRRGRBBBRGGBGGGRRBGBBGRRBRRGBRGRGBRGBRBRGBBGBBGBGBRBRBGBRRGRRBRRBGBRGGRGRGRGGRBGBRRBGBRGBGGBBGRRRRRRRGBGGRGGGGRBGRGGBRRGRRBRBBRGRBBBRGRRBGRBGBGGGGGGRGBGGBGGGBGRRRGRGRRBRBRGGGBRBGBBGRRRGGBRRGRBBGGRGRBRRRBRRRGRGRRBGBGGBBGGGBBBBBRGBRBGBRRGBGRBGRGBBBBRRGRRGRRRBRRGBRGBGBRRGRGRRGRBBBRBGRRRBBBRGGGBBGRGBGGBRRGGGGBRGRRRBBRRRGBBGGBGBBRGBBBRRBGBRRRRRBBRBRGRBRGBGRRRBGGGRR"));
        }
        long stopTime = System.currentTimeMillis();
        long elapsedTimeAVG = stopTime - startTime;
        System.out.println("average run-time per " + tests + " tests: " + elapsedTimeAVG);
        System.out.println("average run-time per test: " + elapsedTimeAVG / tests);
    }

    //used for kata 2 to generate long random string
    protected static String getSaltString() {
        String SALTCHARS = "RGB";
        StringBuilder salt = new StringBuilder();
        Random rnd = new Random();
        while (salt.length() < 1000000) { // length of the random string.
            int index = (int) (rnd.nextFloat() * SALTCHARS.length());
            salt.append(SALTCHARS.charAt(index));
        }
        String saltStr = salt.toString();
        return saltStr;
        
    }
    
    */
}